name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - docs/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
    
    # Build LaTeX file for the book
    - name: Generate LaTeX file
      run: |
        jupyter-book build . --builder latex
    
    # Generate PDF using TeXLive distribution
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: ./_build/latex/
        root_file: book.tex

    # Push the book's PDF to workflow page
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: ./_build/latex/book.pdf